version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/testingofcircleci
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            export SSHPASS="wyScale5NAVtesting"
            scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r routes/ root@167.99.67.107:/var


workflows:
  version: 2
  deploy:
    jobs:
      - deploy
