version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8  # Choose an appropriate Docker image for your needs
    working_directory: ~/testingofcircleci
    steps:
      - checkout
      - run:
          name: Deploy to Server
          command: |
            sudo apt-get install -y sshpass
            sshpass -p 'wyScale5NAVtesting' scp -r routes/ root@167.99.67.107:/var

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
